apiVersion: v1
appVersion: "1.0"
description: |
  A Helm chart for deploying supporting services for the Microservices framework application in Kubernetes
name: microservices-support-project
version: 0.0.1